apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: default
  labels:
    app: booking-service
spec:
  type: ClusterIP
  selector:
    service: booking-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
